wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.6
    code_path: code/train.py
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    viz:
      learning_curve:
        historyFieldSettings:
          key: learning_curve
          x-axis: _step
        id: wandb/learning_curve/v1
      outlier_candidates:
        historyFieldSettings:
          key: outlier_candidates
          x-axis: _step
        id: wandb/outliers/v1
      residuals:
        historyFieldSettings:
          key: residuals
          x-axis: _step
        id: wandb/residuals_plot/v1
      summary_metrics:
        historyFieldSettings:
          key: summary_metrics
          x-axis: _step
        id: wandb/metrics/v1
