name: quality_wine
on: [push]
jobs:
  run:
    runs-on: windows-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      #- uses: actions/setup-node@v3
      #  with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v2
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "<## Model Metrics" > report.md
          cat metrics.txt >>  report.md

          echo "## Data Viz" > report.md
          cml publish feature_importance.png --md >> report.md
          cml publish residual.png --md >> report.md

          cml send-comment report.md
          


          
          
