name: model-wine-quality
on:[push]
jobs:
  run:
    runs-on:[ubuntu-latest]
    steps:
      - users: actions/checkout@v2
      - name: cml_run
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "MODEL METRICS"
          cat metrics.txt
