name: PR Comment

on:
  pull_request:

jobs:
  PR-Comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get run URL
      run: |
        body=$(<run.txt)
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'Accept: application/vnd.github.v3+json' \
        --data '{
          "body": "$body"
          }'